create table if not exists public.site_config (
  id integer primary key default 1 check (id = 1),
  name text not null default 'Tasty Bites',
  heading text not null default 'Hungry? Pick your favourite.',
  sub text not null default 'Fresh food, made to order. Sold-out items are greyed out.',
  accent text not null default '#e4572e',
  cur text not null default '₹',
  foot text not null default '© Tasty Bites · Front-end demo'
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  n text not null,
  p numeric(10, 2) not null default 0 check (p >= 0),
  e text not null default '🍽️',
  d text not null default '',
  s boolean not null default true,
  o bigint generated by default as identity,
  img text not null default ''
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade
);

grant usage on schema public to anon, authenticated;
grant select on public.site_config, public.menu_items to anon, authenticated;
grant update on public.site_config to authenticated;
grant insert, update, delete on public.menu_items to authenticated;
revoke all on public.admin_users from anon;
grant select on public.admin_users to authenticated;

alter table public.site_config enable row level security;
alter table public.menu_items enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public can read site config" on public.site_config;
create policy "Public can read site config"
  on public.site_config for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins can update site config" on public.site_config;
create policy "Admins can update site config"
  on public.site_config for update
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists "Public can read menu items" on public.menu_items;
create policy "Public can read menu items"
  on public.menu_items for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins can insert menu items" on public.menu_items;
create policy "Admins can insert menu items"
  on public.menu_items for insert
  to authenticated
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists "Admins can update menu items" on public.menu_items;
create policy "Admins can update menu items"
  on public.menu_items for update
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists "Admins can delete menu items" on public.menu_items;
create policy "Admins can delete menu items"
  on public.menu_items for delete
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists "Admins can check their own admin account" on public.admin_users;
create policy "Admins can check their own admin account"
  on public.admin_users for select
  to authenticated
  using (user_id = (select auth.uid()));

insert into public.site_config (id)
values (1)
on conflict (id) do nothing;

insert into public.menu_items (n, p, e, d, s, o)
select seed.n, seed.p, seed.e, seed.d, seed.s, seed.o
from (values
  ('Classic Burger', 199, '🍔', 'Juicy patty, cheese, lettuce, house sauce.', true, 1),
  ('Margherita Pizza', 349, '🍕', 'Wood-fired base, mozzarella, fresh basil.', true, 2),
  ('Chicken Biryani', 279, '🍛', 'Fragrant basmati rice with spiced chicken.', false, 3),
  ('Veg Noodles', 169, '🍜', 'Stir-fried noodles with crunchy veggies.', true, 4),
  ('Tacos (2 pcs)', 149, '🌮', 'Crispy shells, salsa, and creamy filling.', true, 5),
  ('French Fries', 99, '🍟', 'Golden, salted, and extra crispy.', false, 6),
  ('Sushi Platter', 449, '🍣', 'Assorted rolls with soy and wasabi.', true, 7),
  ('Garden Salad', 129, '🥗', 'Greens, tomato, cucumber, light dressing.', true, 8),
  ('Chocolate Donut', 79, '🍩', 'Soft, glazed, and loaded with chocolate.', true, 9),
  ('Ice Cream Sundae', 119, '🍨', 'Three scoops with sauce and sprinkles.', false, 10),
  ('Fresh Orange Juice', 89, '🍊', 'Squeezed fresh, no added sugar.', true, 11),
  ('Iced Coffee', 109, '🧋', 'Cold brew over ice with a splash of milk.', true, 12)
) as seed(n, p, e, d, s, o)
where not exists (select 1 from public.menu_items);

select setval(
  pg_get_serial_sequence('public.menu_items', 'o'),
  coalesce((select max(o) from public.menu_items), 1),
  true
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'menu-images',
  'menu-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view menu images" on storage.objects;
create policy "Public can view menu images"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'menu-images');

drop policy if exists "Admins can upload menu images" on storage.objects;
create policy "Admins can upload menu images"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'menu-images'
    and exists (select 1 from public.admin_users where user_id = (select auth.uid()))
  );

drop policy if exists "Admins can update menu images" on storage.objects;
create policy "Admins can update menu images"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'menu-images'
    and exists (select 1 from public.admin_users where user_id = (select auth.uid()))
  )
  with check (
    bucket_id = 'menu-images'
    and exists (select 1 from public.admin_users where user_id = (select auth.uid()))
  );

drop policy if exists "Admins can delete menu images" on storage.objects;
create policy "Admins can delete menu images"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'menu-images'
    and exists (select 1 from public.admin_users where user_id = (select auth.uid()))
  );
